# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Самарина Яна
title: Java-разработчик
address: Россия, Санкт-Петербург
email: yanasamarina1@gmail.com
phone: +79242481851

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Samarinaf
# stackoverflow_username: "00000001"
# instagram_username: jameswgrant
linkedin_username: yana-samarina

# Additional icon links
additional_links:
- title: Telegram link
  icon: fab fa-telegram
  url: https://t.me/yana_samarina
- title: Skype link
  icon: fab fa-skype
  url: https://join.skype.com/invite/bgHObg3BSxGb

# About Section
about_title: Ключевые навыки
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs  
 
content:
  - title: Проекты # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Restaurant Voting System
        link: https://github.com/Samarinaf/topjava_graduation
        # link_text: Project Website
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #   icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
       # quote: >
       #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Разработка собственного выпускного проекта с нуля: REST API (система голосования за рестораны), на стеке Java 15, Spring (MVC, Security, Data JPA), Hibernate, REST(Jackson), JUnit 5, HSQLDB, Maven, Git, Tomcat без front-end.
  
  
  - title: Опыт работы # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Java Online Projects
        link: https://javaops.ru/view/topjava
        # link_text: boringcompany.com
        sub_title: Java-разработчик
        caption: январь 2021  - май 2021
        # quote: >
        # url: Link to project 
        description: | # this will include new lines to allow paragraphs
           Участие в разработке Spring/JPA Enterprise приложения c авторизацией и правами доступа на основе ролей, на стеке Maven/ Spring MVC/ Security/ REST(Jackson)/ Java 8 Stream API:
           - реализация сохранения в Postgres и HSQLDB на основе Spring JBDC, JPA(Hibernate) и Spring-Data-JPA,
           - реализация и тестирование REST и AJAX контроллеров,
           - реализация клиента на Bootstrap (css/js), datatables, jQuery + plugins,
           - собственная доработка проекта,
           - [Ссылка на GitHub](https://github.com/Samarinaf/topjava)   
        
  
  - title: Образование # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ВИАКАДЕМИЯ, институт переподготовки и повышения квалификации
        caption: 2021
        # sub_title: Enterprise Java-разработчик
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
         Enterprise Java-разработчик
      - layout: top-middle
        title: Филиал Дальневосточного федерального университета, Уссурийск
        caption: 2009-2014
        # sub_title: Преподаватель иностранных языков (английского и немецкого)
        description: | 
         Преподаватель иностранных языков (английского и немецкого)
        
        
 # - title: A Little More About Me
 #  layout: text
 #   content: | # this will include new lines to allow paragraphs
 #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
 #     - Rock climbing
 #     - Gaming
 #     - Knitting
 #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
