# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Самарина Яна
title: Java-разработчик
address: Россия, Санкт-Петербург
email: yanasamarina1@gmail.com
phone: 8(924)248-18-51

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  Samarinaf
linkedin_username: yana-samarina

# Additional icon links
additional_links:
- title: Telegram link
  icon: fab fa-telegram
  url: https://t.me/yana_samarina
- title: Skype link
  icon: fab fa-skype
  url: https://join.skype.com/invite/bgHObg3BSxGb

# About Section
about_title: Ключевые навыки
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs 
 - Java 8+ (Core, Multithreading, Collections, Stream/Time API);
 - Frameworks: Spring (MVC, Data JPA, Security, Boot), Hibernate ORM, JUnit;
 - DB: PostgreSQL, MySQL, HSQLDB;
 - Технологии: Servlets, JSP/JSTL, JDBC, REST, JPA;
 - Инструменты: Git, Maven, Postman, Tomcat, IntelliJ IDEA.
 
content:
  - title: Проекты # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Restaurant Voting System
        link: https://github.com/Samarinaf/topjava_graduation       
        description: | # this will include new lines to allow paragraphs
          Разработка выпускного проекта с нуля: REST API (система голосования за рестораны), на стеке Java 15, Spring (MVC, Security, Data JPA), Hibernate, REST(Jackson), JUnit 5, HSQLDB, Maven, Git, Tomcat без front-end.
  
  
  - title: Опыт работы # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Java Online Projects
        link: https://javaops.ru/view/topjava
        # link_text: boringcompany.com
        sub_title: Java-разработчик
        caption: январь 2021  - май 2021       
        description: | # this will include new lines to allow paragraphs
           Участие в разработке Spring/JPA Enterprise приложения c авторизацией и правами доступа на основе ролей, на стеке Maven/ Spring MVC/ Security/ REST(Jackson)/ Java 8 Stream API:
           - реализация сохранения в Postgres и HSQLDB на основе Spring JBDC, JPA(Hibernate) и Spring-Data-JPA,
           - реализация и тестирование REST и AJAX контроллеров,
           - реализация клиента на Bootstrap (css/js), datatables, jQuery + plugins,
           - собственная доработка проекта,
           - [Ссылка на GitHub](https://github.com/Samarinaf/topjava)   
        
  
  - title: Образование # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ВИАКАДЕМИЯ
        caption: 2021        
        description: | # this will include new lines to allow paragraphs
         Enterprise Java-разработчик
      - layout: left
        title: ДВФУ
        caption: 2009-2014
        description: | 
         Преподаватель иностранных языков (английского и немецкого)
        
        
  - title: Курсы, сертификаты
    layout: text
    content: | # this will include new lines to allow paragraphs
     - JavaRush, Онлайн курс обучения программированию на Java (Syntax, Core, Multithreading, Collections) 
     - Udemy:
     - Java Database Connection: JDBC and MySQL,
     - Spring для начинающих,
     - Git: Полный курс для начинающих и не только,
     - Продвинутая Java
     - LevelUp, Основы программирования на языке Java. Уровень 2

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
